spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contadoria_test
    username: postgres
    password: 1
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop

